### ISSUE TITLE
No beatmap found?

### ISSUE THREAD

**Issue by minhducsun2002** [nahkd123/osu-replay-viewer#2]
I encountered this error upon trying to view a local replay :
```
Beatmap not found while opening replay: No corresponding beatmap for the score could be found.
```

Where should I put the relevant beatmap to? And should I just put the `.osu` file, the referenced audio files/background images, or the whole mapset?

I don't think providing a replay is relevant - I tried with three different replays on three different maps.

For the context, I'm on Linux, and `dotnet --version` yields `5.0.205`.

**Comment by nahkd123** [comment]
This one is like platform-dependent issue, where the game attempt to load data at wrong location.

Have you tried listing all available replays using command yet? It's ``osu-replay-viewer list``. Don't forget to import replays to osu!lazer

**Comment by nahkd123** [comment]
If the ``list`` command shows nothing, you might want to try [``platform-independent``](https://github.com/nahkd123/osu-replay-viewer/tree/platform-independent) branch. Basically it will uses the correct storage path depends on platform.

**Comment by nahkd123** [comment]
Ok so I've installed Linux VM and replay viewer is working fine without ``platform-independent`` branch.

To watch the replay, you need to install beatmap to your current osu!lazer installation. This replay viewer works by impersonating the client so it can read beatmaps data.

I might have to add another option for loading beatmap from file instead of reading from game storage.
